DIALECT_MYSQL = "mysql"
DRIVER_PYMYSQL = "pymysql"

# ---------- CUrW Fcst Database --------------
CURW_FCST_USERNAME = "root"
CURW_FCST_PASSWORD = "cfcwm07"
CURW_FCST_HOST = "35.230.102.148"
CURW_FCST_PORT = 3306
CURW_FCST_DATABASE = "curw_fcst"

# CURW_FCST_USERNAME = "root"
# CURW_FCST_PASSWORD = "password"
# CURW_FCST_HOST = "127.0.0.1"
# CURW_FCST_PORT = 3306
# CURW_FCST_DATABASE = "curw_fcst"